name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"  # Déclenche le workflow à chaque push sur toutes les branches
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour l'exécution du workflow

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action pour récupérer le code du dépôt